/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AcompanharPedidoRouteImport } from './routes/acompanhar-pedido'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as FaleConoscoRouteImport } from './routes/fale-conosco'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as PoliticaDeTrocasRouteImport } from './routes/politica-de-trocas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFunisRouteImport } from './routes/_authenticated/funis'
import { Route as AuthenticatedLucroPrejuizoRouteImport } from './routes/_authenticated/lucro-prejuizo'
import { Route as ColecaoBrandRouteImport } from './routes/colecao/$brand'
import { Route as ProdutoSlugRouteImport } from './routes/produto/$slug'
import { Route as ApiPublicFreepayWebhookRouteImport } from './routes/api/public/freepay-webhook'
import { Route as ApiPublicGatewayRouteImport } from './routes/api/public/gateway'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiPublicPresenceRouteImport } from './routes/api/public/presence'
import { Route as ApiPublicReceiptRouteImport } from './routes/api/public/receipt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanharPedidoRoute = AcompanharPedidoRouteImport.update({
  id: '/acompanhar-pedido',
  path: '/acompanhar-pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const FaleConoscoRoute = FaleConoscoRouteImport.update({
  id: '/fale-conosco',
  path: '/fale-conosco',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeTrocasRoute = PoliticaDeTrocasRouteImport.update({
  id: '/politica-de-trocas',
  path: '/politica-de-trocas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFunisRoute = AuthenticatedFunisRouteImport.update({
  id: '/funis',
  path: '/funis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLucroPrejuizoRoute =
  AuthenticatedLucroPrejuizoRouteImport.update({
    id: '/lucro-prejuizo',
    path: '/lucro-prejuizo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ColecaoBrandRoute = ColecaoBrandRouteImport.update({
  id: '/colecao/$brand',
  path: '/colecao/$brand',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFreepayWebhookRoute = ApiPublicFreepayWebhookRouteImport.update({
  id: '/api/public/freepay-webhook',
  path: '/api/public/freepay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGatewayRoute = ApiPublicGatewayRouteImport.update({
  id: '/api/public/gateway',
  path: '/api/public/gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPresenceRoute = ApiPublicPresenceRouteImport.update({
  id: '/api/public/presence',
  path: '/api/public/presence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReceiptRoute = ApiPublicReceiptRouteImport.update({
  id: '/api/public/receipt',
  path: '/api/public/receipt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acompanhar-pedido': typeof AcompanharPedidoRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/pagamento': typeof PagamentoRoute
  '/politica-de-trocas': typeof PoliticaDeTrocasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/funis': typeof AuthenticatedFunisRoute
  '/lucro-prejuizo': typeof AuthenticatedLucroPrejuizoRoute
  '/colecao/$brand': typeof ColecaoBrandRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/freepay-webhook': typeof ApiPublicFreepayWebhookRoute
  '/api/public/gateway': typeof ApiPublicGatewayRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/presence': typeof ApiPublicPresenceRoute
  '/api/public/receipt': typeof ApiPublicReceiptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acompanhar-pedido': typeof AcompanharPedidoRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/pagamento': typeof PagamentoRoute
  '/politica-de-trocas': typeof PoliticaDeTrocasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/funis': typeof AuthenticatedFunisRoute
  '/lucro-prejuizo': typeof AuthenticatedLucroPrejuizoRoute
  '/colecao/$brand': typeof ColecaoBrandRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/freepay-webhook': typeof ApiPublicFreepayWebhookRoute
  '/api/public/gateway': typeof ApiPublicGatewayRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/presence': typeof ApiPublicPresenceRoute
  '/api/public/receipt': typeof ApiPublicReceiptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acompanhar-pedido': typeof AcompanharPedidoRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/pagamento': typeof PagamentoRoute
  '/politica-de-trocas': typeof PoliticaDeTrocasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/funis': typeof AuthenticatedFunisRoute
  '/_authenticated/lucro-prejuizo': typeof AuthenticatedLucroPrejuizoRoute
  '/colecao/$brand': typeof ColecaoBrandRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/freepay-webhook': typeof ApiPublicFreepayWebhookRoute
  '/api/public/gateway': typeof ApiPublicGatewayRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/presence': typeof ApiPublicPresenceRoute
  '/api/public/receipt': typeof ApiPublicReceiptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acompanhar-pedido'
    | '/auth'
    | '/checkout'
    | '/fale-conosco'
    | '/pagamento'
    | '/politica-de-trocas'
    | '/dashboard'
    | '/funis'
    | '/lucro-prejuizo'
    | '/colecao/$brand'
    | '/produto/$slug'
    | '/api/public/freepay-webhook'
    | '/api/public/gateway'
    | '/api/public/ingest'
    | '/api/public/presence'
    | '/api/public/receipt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acompanhar-pedido'
    | '/auth'
    | '/checkout'
    | '/fale-conosco'
    | '/pagamento'
    | '/politica-de-trocas'
    | '/dashboard'
    | '/funis'
    | '/lucro-prejuizo'
    | '/colecao/$brand'
    | '/produto/$slug'
    | '/api/public/freepay-webhook'
    | '/api/public/gateway'
    | '/api/public/ingest'
    | '/api/public/presence'
    | '/api/public/receipt'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acompanhar-pedido'
    | '/auth'
    | '/checkout'
    | '/fale-conosco'
    | '/pagamento'
    | '/politica-de-trocas'
    | '/_authenticated/dashboard'
    | '/_authenticated/funis'
    | '/_authenticated/lucro-prejuizo'
    | '/colecao/$brand'
    | '/produto/$slug'
    | '/api/public/freepay-webhook'
    | '/api/public/gateway'
    | '/api/public/ingest'
    | '/api/public/presence'
    | '/api/public/receipt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcompanharPedidoRoute: typeof AcompanharPedidoRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  FaleConoscoRoute: typeof FaleConoscoRoute
  PagamentoRoute: typeof PagamentoRoute
  PoliticaDeTrocasRoute: typeof PoliticaDeTrocasRoute
  ColecaoBrandRoute: typeof ColecaoBrandRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ApiPublicFreepayWebhookRoute: typeof ApiPublicFreepayWebhookRoute
  ApiPublicGatewayRoute: typeof ApiPublicGatewayRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicPresenceRoute: typeof ApiPublicPresenceRoute
  ApiPublicReceiptRoute: typeof ApiPublicReceiptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhar-pedido': {
      id: '/acompanhar-pedido'
      path: '/acompanhar-pedido'
      fullPath: '/acompanhar-pedido'
      preLoaderRoute: typeof AcompanharPedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fale-conosco': {
      id: '/fale-conosco'
      path: '/fale-conosco'
      fullPath: '/fale-conosco'
      preLoaderRoute: typeof FaleConoscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-trocas': {
      id: '/politica-de-trocas'
      path: '/politica-de-trocas'
      fullPath: '/politica-de-trocas'
      preLoaderRoute: typeof PoliticaDeTrocasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funis': {
      id: '/_authenticated/funis'
      path: '/funis'
      fullPath: '/funis'
      preLoaderRoute: typeof AuthenticatedFunisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lucro-prejuizo': {
      id: '/_authenticated/lucro-prejuizo'
      path: '/lucro-prejuizo'
      fullPath: '/lucro-prejuizo'
      preLoaderRoute: typeof AuthenticatedLucroPrejuizoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/colecao/$brand': {
      id: '/colecao/$brand'
      path: '/colecao/$brand'
      fullPath: '/colecao/$brand'
      preLoaderRoute: typeof ColecaoBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/freepay-webhook': {
      id: '/api/public/freepay-webhook'
      path: '/api/public/freepay-webhook'
      fullPath: '/api/public/freepay-webhook'
      preLoaderRoute: typeof ApiPublicFreepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gateway': {
      id: '/api/public/gateway'
      path: '/api/public/gateway'
      fullPath: '/api/public/gateway'
      preLoaderRoute: typeof ApiPublicGatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/presence': {
      id: '/api/public/presence'
      path: '/api/public/presence'
      fullPath: '/api/public/presence'
      preLoaderRoute: typeof ApiPublicPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/receipt': {
      id: '/api/public/receipt'
      path: '/api/public/receipt'
      fullPath: '/api/public/receipt'
      preLoaderRoute: typeof ApiPublicReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFunisRoute: typeof AuthenticatedFunisRoute
  AuthenticatedLucroPrejuizoRoute: typeof AuthenticatedLucroPrejuizoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFunisRoute: AuthenticatedFunisRoute,
  AuthenticatedLucroPrejuizoRoute: AuthenticatedLucroPrejuizoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcompanharPedidoRoute: AcompanharPedidoRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  FaleConoscoRoute: FaleConoscoRoute,
  PagamentoRoute: PagamentoRoute,
  PoliticaDeTrocasRoute: PoliticaDeTrocasRoute,
  ColecaoBrandRoute: ColecaoBrandRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ApiPublicFreepayWebhookRoute: ApiPublicFreepayWebhookRoute,
  ApiPublicGatewayRoute: ApiPublicGatewayRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicPresenceRoute: ApiPublicPresenceRoute,
  ApiPublicReceiptRoute: ApiPublicReceiptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
